# Generated by Django 4.0.6 on 2022-08-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wemes.type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
