# Generated by Django 4.0.6 on 2022-08-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0002_qrcode_type_alter_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='type',
        ),
    ]
