# Generated by Django 4.0.6 on 2022-08-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0003_remove_qrcode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.ImageField(blank=True, upload_to='./wemes/static'),
        ),
    ]
