# Generated by Django 4.0.6 on 2022-08-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0004_alter_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
