# Generated by Django 4.0.6 on 2022-08-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0005_remove_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
