# Generated by Django 4.0.6 on 2022-08-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0007_item_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag_id',
        ),
    ]
